/**
 * Parser is responsible for parsing the string content generated by LLM into DSL in a specific format (JSON or YAML)
 * Use a transformer to complete the conversion from string to DSL
 * Pass in the transformer during initialization
 */
export type Parser<Input, DSL> = (input: Input) => DSL;
